#SET CHECKS TO 0 IN ORDER TO DROP TABLES WITHOUT PROBLEM
SET FOREIGN_KEY_CHECKS=0;

CREATE DATABASE IF NOT EXISTS coursesManagmentAppDB;
USE coursesManagmentAppDB;

DROP TABLE IF EXISTS StudentRegistration;
DROP TABLE IF EXISTS Course;

#SET BACK TO 1 IN ORDER TO CHECK FOR FOREIGN KEY ERRORS
SET FOREIGN_KEY_CHECKS=1;

CREATE TABLE Course (
	id INT NOT NULL AUTO_INCREMENT,
    coursename VARCHAR(40) DEFAULT NULL,
    semester VARCHAR(10) DEFAULT 1,
    period VARCHAR(10) DEFAULT NULL,
    ects VARCHAR(3)	DEFAULT NULL,
    ctype VARCHAR(30) DEFAULT NULL,
    projectper VARCHAR(3) DEFAULT NULL,
    examper VARCHAR(3) DEFAULT NULL,
    PRIMARY KEY (id)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE TABLE StudentRegistration (
	id INT NOT NULL AUTO_INCREMENT,
    courseid INT NOT NULL,
    am VARCHAR(4) NOT NULL,
    studentname VARCHAR(50) DEFAULT NULL,
    yearofreg VARCHAR(5) DEFAULT NULL,
    currsemester VARCHAR(3) DEFAULT NULL,
    projectgrade VARCHAR(3) DEFAULT NULL,
    examgrade VARCHAR(3) DEFAULT NULL,
    finalgrade VARCHAR(3) DEFAULT NULL,
    PRIMARY KEY (id),
	FOREIGN KEY (courseid) REFERENCES Course (id)
		ON DELETE CASCADE
        ON UPDATE CASCADE
)ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;
